.circleci/config.yml

Forked PRs aren't building anything because `$VERSIONS`is empty (I thought `VERSIONS=` would've been ignored by make, oops): https://circleci.com/gh/rstudio/r-docker/174
Rather than handling an empty `$VERSIONS` variable, I thought we could just build everything. Apparently open source projects get 4 concurrent jobs on CircleCI instead of just 1, so builds run a lot faster now. And it would be easier to not have to maintain `VERSIONS` anyway.

Build all R versions in CircleCI

---

Makefile

Adds bash targets to `Makefile` so you can easily use something like `make bash-3.5-xenial` to get a shell.

Add bash targets

---

test/test.R

Minor change to the tests so they can be used elsewhere more easily, like:
```sh
R -e 'source("https://raw.githubusercontent.com/rstudio/r-docker/master/test/test.R")'
```
I've been using this to test the Debian 9 installer.

Make tests more portable

---

3.1/centos7/Dockerfile
3.2/centos7/Dockerfile
3.3/centos7/Dockerfile
3.4/centos7/Dockerfile
3.5/centos7/Dockerfile
3.6/centos7/Dockerfile
Dockerfile-centos.template
base/centos7/Dockerfile

Diff of the image before and after:
```sh
$ container-diff diff -n daemon://rstudio/r-base:3.5-centos7 daemon://r-base-rpm:3.5-centos7 --type=size --type=rpm
-----RPM-----
Packages found only in rstudio/r-base:3.5-centos7:
NAME                         VERSION             SIZE
-apr                         1.4.8               221.4K
-apr-util                    1.5.2               194.1K
-autoconf                    2.69                2.2M
-automake                    1.13.4              1.7M
-avahi-libs                  0.6.31              120.9K
-bison                       3.0.4               2.1M
-boost-date-time             1.53.0              136.4K
-boost-system                1.53.0              31.8K
-boost-thread                1.53.0              93.4K
-byacc …
```

Install R from rpm on CentOS 7

---

3.1/opensuse15/Dockerfile
3.1/opensuse42/Dockerfile
3.2/opensuse15/Dockerfile
3.2/opensuse42/Dockerfile
3.3/opensuse15/Dockerfile
3.3/opensuse42/Dockerfile
3.4/opensuse15/Dockerfile
3.4/opensuse42/Dockerfile
3.5/opensuse15/Dockerfile
3.5/opensuse42/Dockerfile
3.6/opensuse15/Dockerfile
3.6/opensuse42/Dockerfile
Dockerfile-opensuse.template
base/opensuse15/Dockerfile
base/opensuse42/Dockerfile

Image diff for opensuse42:
```
$ container-diff diff -n daemon://rstudio/r-base:3.5-opensuse42 daemon://r-base-rpm:3.5-opensuse42 --type=size --type=rpm
-----RPM-----
Packages found only in rstudio/r-base:3.5-opensuse42:
NAME                      VERSION         SIZE
-perl-Net-DBus            1.0.0           569K
-perl-X11-Protocol        0.56            288.7K
-perl-XML-Parser          2.41            630.2K
-perl-XML-Twig            3.44            1.1M
-xdg-utils                20160610        341.7K
Packages found only in r-base-rpm:3.5-opensuse42:
NAME            VERSION        SIZE
-R-3.5.3        1              92.3M
-unzip          6.00           263K
-zip            3.0            790.5K
Version differences: None
-----Size-----
Image size difference between …
```

Install R from rpm on openSUSE

---

base/bionic/Dockerfile
base/centos6/Dockerfile
base/centos7/Dockerfile
base/opensuse15/Dockerfile
base/opensuse42/Dockerfile
base/xenial/Dockerfile
test/test.R

Set `TZ=UTC` to prevent a couple issues with using `Sys.timezone()`:
- `Sys.timezone()` returns a warning on R >= 3.4 with `timedatectl` present
- `Sys.timezone()` returns a warning on R >= 3.4 with CentOS 6
- `Sys.timezone()` returns NA on R <= 3.3 with CentOS 6
Resolves https://github.com/rstudio/r-docker/issues/46

Set the TZ environment variable

---

.circleci/config.yml
3.1/focal/Dockerfile
3.1/focal/docker-compose.test.yml
3.1/focal/hooks/post_push
3.2/focal/Dockerfile
3.2/focal/docker-compose.test.yml
3.2/focal/hooks/post_push
3.3/focal/Dockerfile
3.3/focal/docker-compose.test.yml
3.3/focal/hooks/post_push
3.4/focal/Dockerfile
3.4/focal/docker-compose.test.yml
3.4/focal/hooks/post_push
3.5/focal/Dockerfile
3.5/focal/docker-compose.test.yml
3.5/focal/hooks/post_push
3.6/focal/Dockerfile
3.6/focal/docker-compose.test.yml
3.6/focal/hooks/post_push
4.0/focal/Dockerfile
4.0/focal/docker-compose.test.yml
4.0/focal/hooks/post_push
Makefile
README.md
base/bionic/Dockerfile
base/focal/Dockerfile
base/xenial/Dockerfile
update.sh

Add images for Ubuntu 20.04 Focal.
Also remove some redundant system packages from Ubuntu 16/18 that are now included via R binaries: libpcre, libicu, libbz2, liblzma, zlib1g: https://github.com/rstudio/r-builds/pull/63/files#diff-f662e6debfa6739a09cb46d54c95735aL23
From a container diff, there should be no difference except that the new image only includes either one of libpcre2 (PCRE 2 for R 4.0+) or libpcre3 (PCRE 1 for R 3.6 and below), not both:
```sh
$ container-diff diff daemon://rstudio/r-base:3.6-bionic daemon://r-base-test:3.6-bionic --type=apt
-----Apt-----
Packages found only in rstudio/r-base:3.6-bionic:
NAME                    VERSION        SIZE
-libpcre2-16-0          10.31-2        491K
-libpcre2-32-0          10.31-2        471K
-libpcre2-8-0           10.31-2 …
```

Add Ubuntu 20.04 Focal

---

.circleci/config.yml
Makefile
devel/bionic/Dockerfile
devel/bionic/docker-compose.test.yml
devel/bionic/hooks/post_push
devel/centos6/Dockerfile
devel/centos6/docker-compose.test.yml
devel/centos6/hooks/post_push
devel/centos7/Dockerfile
devel/centos7/docker-compose.test.yml
devel/centos7/hooks/post_push
devel/centos8/Dockerfile
devel/centos8/docker-compose.test.yml
devel/centos8/hooks/post_push
devel/focal/Dockerfile
devel/focal/docker-compose.test.yml
devel/focal/hooks/post_push
devel/opensuse15/Dockerfile
devel/opensuse15/docker-compose.test.yml
devel/opensuse15/hooks/post_push
devel/opensuse42/Dockerfile
devel/opensuse42/docker-compose.test.yml
devel/opensuse42/hooks/post_push
devel/xenial/Dockerfile
devel/xenial/docker-compose.test.yml
devel/xenial/hooks/post_push
update.sh

For https://github.com/rstudio/r-docker/issues/39:
- Adds R-devel images. R-devel binaries are now being built daily at around 4 AM UTC: https://github.com/rstudio/r-builds/pull/71
- Schedules R-devel images to be built daily at 6 AM UTC. The CircleCI config changes for this are kind of ugly, but I believe it works. In particular, CircleCI limits where you can set environment variables vs. parameters, so parameterization is done through a mix of environment variables and build parameters.

Add R-devel images

---

.circleci/config.yml
3.1/opensuse152/Dockerfile
3.1/opensuse152/docker-compose.test.yml
3.1/opensuse152/hooks/post_push
3.2/opensuse152/Dockerfile
3.2/opensuse152/docker-compose.test.yml
3.2/opensuse152/hooks/post_push
3.3/opensuse152/Dockerfile
3.3/opensuse152/docker-compose.test.yml
3.3/opensuse152/hooks/post_push
3.4/opensuse152/Dockerfile
3.4/opensuse152/docker-compose.test.yml
3.4/opensuse152/hooks/post_push
3.5/opensuse152/Dockerfile
3.5/opensuse152/docker-compose.test.yml
3.5/opensuse152/hooks/post_push
3.6/opensuse152/Dockerfile
3.6/opensuse152/docker-compose.test.yml
3.6/opensuse152/hooks/post_push
4.0/opensuse152/Dockerfile
4.0/opensuse152/docker-compose.test.yml
4.0/opensuse152/hooks/post_push
Makefile
README.md
base/opensuse152/Dockerfile
devel/opensuse152/Dockerfile
devel/opensuse152/docker-compose.test.yml
devel/opensuse152/hooks/post_push
update.sh

Now that openSUSE 15.2 R binaries are available (https://github.com/rstudio/r-builds/pull/73), we can add images for openSUSE 15.2.

Add images for openSUSE 15.2

---

.circleci/config.yml
Makefile
README.md

- Adds support for building R patch versions
- Adds a CI job that rebuilds all patch versions once a month, so that they're actively maintained and updated with security patches (e.g., Baron Samedit sudo vulnerability). I think this job can also be manually triggered via the CircleCI console if needed.
Currently supported patch versions are just the tags available on Docker Hub, which are R 3.6.0, 3.6.1, 3.6.2, 3.6.3, 4.0.0, 4.0.1, 4.0.2, 4.0.3, and all the latest patch versions from R 3.5 and below. It's a large matrix and the job currently takes 2+ hours, but at least there are only a few R releases a year, and the job only runs once a month. Here's a one-off build I did on another branch: https://app.circleci.com/pipelines/github/rstudio/r-docker/355/workflows/761bfc85-5d6f-40e8-9c77-22 …

Build and maintain R patch versions

---

.github/workflows/build.yml

Update GHA for https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
(The opensuse154 failure is a known issue with failing R-devel builds)

Update GHA for set-output deprecation

---

base/bookworm/Dockerfile
base/bullseye/Dockerfile
base/centos7/Dockerfile
base/focal/Dockerfile
base/jammy/Dockerfile
base/opensuse154/Dockerfile
base/opensuse155/Dockerfile
base/rockylinux8/Dockerfile
base/rockylinux9/Dockerfile
test/test.sh

Pandoc 1 is old and no longer available from R-Hub. System Pandoc versions all differ from 1.x to 2.x, so install the final Pandoc 2.x static binaries from https://github.com/jgm/pandoc/releases/tag/2.19.2. pandoc-citeproc is no longer needed. We don't expect any breaking changes moving from Pandoc 1 to 2 here.
Here are the system pandoc versions for reference:
- focal: 2.5
- jammy: 2.9.2
- centos7: 1.12.3
- rockylinux8: 2.0.6 (powertools)
- rockylinux9: 2.14.0 (EPEL)
- opensuse154: 2.17
- opensuse155: 2.18

Fix Pandoc install; Update to Pandoc 2.19.2

---

base/centos7/Dockerfile

Fix the daily R-devel builds for CentOS 7, use vault for mirrors since CentOS 7 is now EOL.

Fix CentOS 7 builds; Use vault.centos.org on CentOS 7 for EOL

---

test/testpkg/src/add.c
test/testpkg/src/subtract.cpp

These tests have been failing since November:
```r
g++ -std=gnu++11 -I"/opt/R/devel/lib/R/include" -DNDEBUG   -I/usr/local/include    -fpic  -g -O2  -DR_NO_REMAP -c subtract.cpp -o subtract.o
In file included from subtract.cpp:2:
subtract.cpp: In function ‘SEXPREC* subtract(SEXP, SEXP)’:
subtract.cpp:6:25: error: ‘allocVector’ was not declared in this scope; did you mean ‘Rf_allocVector’?
6 |   SEXP result = PROTECT(allocVector(REALSXP, 1));
|                         ^~~~~~~~~~~
/opt/R/devel/lib/R/include/Rinternals.h:388:36: note: in definition of macro ‘PROTECT’
388 | #define PROTECT(s)      Rf_protect(s)
|                                    ^
subtract.cpp:7:21: error: ‘asReal’ was not declared in this scope
7 |   REAL(result)[0] = asReal(a) - asReal(b);
|                     ^~~~~~ …
```

Fix R-devel tests, fix R API calls for R 4.5.0 R_NO_REMAP changes

---

.github/workflows/build.yml
Dockerfile-centos.template
Dockerfile-debian.template
Dockerfile-opensuse.template
Dockerfile-rockylinux.template
Dockerfile-ubuntu.template
Makefile
README.md

This migrates the main DockerHub repo from `rstudio/r-base` to `posit/r-base`. It continues to push to `rstudio/r-base` and adds a note about future deprecation of that repo.

chore: rstudio/r-base to posit/r-base

---

.github/workflows/build.yml
Makefile

I noticed that the images are not being properly pushed to the `rstudio/r-base` repo with the changes I made adding the `posit/r-base` as the `BASE_IMAGE`. I removed what I added before because it felt messy and instead added the repo/org secrets as part of the GHA build matrix. This should ensure each image is being built and tagged properly, and then authenticating and pushing to the correct repo.
The build matrix looks like this now:
```json
{
"include": [
{
"variant": "focal",
"username_secret": "DOCKERHUB_USERNAME",
"token_secret": "DOCKERHUB_TOKEN",
"repo": "posit/r-base"
},
{
"variant": "focal",
"username_secret": "RSTUDIO_DOCKERHUB_USERNAME",
"token_secret": "RSTUDIO_DOCKERHUB_TOKEN",
"repo": "rstudio/r-base"
},
{
"variant": "jammy",
"username_secret": "DOCKERHUB_USERNAME", …
```

fix: add repos to build matrix to properly push to each orgs repo

---

.github/workflows/build.yml

This should let all the images get pushed to `posit/r-base` that we need before updating the images that the build cluster uses. The tests that have been failing are only for `opensuse156`, `noble`, and `bookworm`, this should get those to be pushed successfully, then we can fix/re-enable the tests.
Ref https://github.com/rstudio/package-manager/issues/15035

disable image tests for now because they are broken

---

.github/workflows/build.yml

`opensuse155` fails to build and push tags, presumably because of how long it takes and running out of disk space: https://github.com/rstudio/r-docker/actions/runs/13295961698/job/37127876207#logs
This attempts to bump the runner size to mitigate those issues.

use larger gha runner for building images

---

.github/workflows/build.yml
test/test.R

This reverts commit 0872fd07fea93ab82288c66bdb6ff1eec80af547.
R-devel builds were fixed in https://github.com/rstudio/r-builds/pull/244 and rebuilt.
CI is probably going to fail for a few hours until the R-devel packages get invalidated in the CDN

Reenable tests for R-devel fix

---

.github/workflows/build.yml

Going to see if this works as a simple stopgap for the full patch version builds. Trying it out at https://github.com/rstudio/r-docker/actions/runs/13467039052/job/37634850116
This seems to work. The only error there was some transient error with pushing to Docker Hub rather than a disk space issue.

Limit parallel builds to prevent running out of disk space

---

base/rockylinux8/Dockerfile
test/test.sh

`find` is usually installed by default, but not on RHEL/Rocky 8's base image. In this specific case, the s2 package needs it for its config script: https://github.com/r-spatial/s2/blob/1764fe73e54556b98c721df6a8e83d93bf02d83b/configure#L98-L99
find is never specified as a system requirement either, so the best place is probably here in the base image.

Add find command to rockylinux8 base image
